e1:
	gcc -Wall -fopenmp -o encaja-e1{,.c}

e2:
	gcc -Wall -fopenmp -o encaja-e2-pJ{,.c}
	gcc -Wall -fopenmp -o encaja-e2-pX{,.c}

e3:
	gcc -Wall -fopenmp -o encaja-e3{,.c}

e4:
	gcc -Wall -fopenmp -o encaja-e4-pJ{,.c}
	gcc -Wall -fopenmp -o encaja-e4-pX{,.c}

clean:
	rm -vf encaja-e?{-p?}
